volumes:
  cache:
    driver: local

services:
  usersservice:
    image: stoplight/prism:4
    ports:
      - 14015:4010
    command: ["mock","-h","0.0.0.0","https://raw.githubusercontent.com/friendpost-july/user-spec/main/user_spec.yml"]

  postsservice:
    image: stoplight/prism:4
    ports:
      - 14011:4010
    command: ["mock","-h","0.0.0.0","https://raw.githubusercontent.com/friendpost-july/post-management-spec/main/post-spec.yml"]

  friendsservice:
    image: stoplight/prism:4
    ports:
      - 14012:4010
    command: ["mock","-h","0.0.0.0","https://raw.githubusercontent.com/friendpost-july/friends-spec/main/openapi.yaml"]

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 18001:8001
    volumes:
      - cache:/data

  timelineservice:
    image: timelineservice:0.1.0
    ports:
      - 15056:15033
    environment:
      - PORT=15033
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POST_SERVICE_ENV=https://postsservice:4010
      - FRIENDS_SERVICE_ENV=https://friendsservice:4010
      - USER_SERVICE_ENV=https://usersservice:4010

  rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    hostname: rmq
    volumes:
      - rmqvol:/var/lib/rabbitmq:rw
    environment:
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_ERLANG_COOKIE=chocochip
